version: "3.3"
services:
  database:
    image: postgres:9.6
    ports:
      - "5432:5432"

  video:
    build: ./videoServer/
    ports:
      - "1935:1935"
    volumes:
      - ./videoServer/project:/project
      - ~/videos:/videos
      
  web:
    build: ./webServer/
    ports:
      - "80:8000"
    volumes:
      - ./webServer/project:/project
    depends_on:
      - database
  
      