version: "3.3"
services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - "~/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    networks:
      - my-net
      
  web:
    build: ./webServer/
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - ./webServer/project:/project
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    command: >
        bash -c " pip install -r /project/requirements.txt
        && python /project/Webserver/manage.py makemigrations
        && python /project/Webserver/manage.py migrate
        && python  /project/Webserver/manage.py runserver 0.0.0.0:8000"
    networks:
      - my-net
  
networks:
  my-net:
      