# Generated by Django 4.0.4 on 2022-06-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('docfile', models.FileField(default='newvid', upload_to='documents/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('positive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BigTeta.video')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='BigTeta.video')),
                ('video_02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='BigTeta.video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='related',
            constraint=models.UniqueConstraint(fields=('video_01', 'video_02'), name='pk_related'),
        ),
    ]
