# Generated by Django 4.0.4 on 2022-06-24 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 9, 57, 45, 985531), null=None),
        ),
        migrations.AddField(
            model_name='video',
            name='date_updated',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 9, 57, 45, 985557), null=None),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
