# Generated by Django 4.0.4 on 2022-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='only_one_vote_per_user'),
        ),
    ]
