# Generated by Django 4.0.4 on 2022-06-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
