# Generated by Django 4.0.4 on 2022-06-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0002_vote_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='docfile',
            field=models.FileField(default='newvid', upload_to='documents/%Y/%m/%d'),
        ),
    ]
