# Generated by Django 4.0.4 on 2022-06-24 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0002_video_date_published_video_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 9, 57, 48, 23713), null=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_updated',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 9, 57, 48, 23742), null=None),
        ),
    ]
