# Generated by Django 4.0.4 on 2022-06-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0003_video_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='urlAuxiliar',
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BigTeta.video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='related',
            constraint=models.UniqueConstraint(fields=('video_01',), name='pk_related'),
        ),
    ]
