# Generated by Django 4.0.4 on 2022-06-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0004_remove_video_filename_remove_video_urlauxiliar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='related',
            name='pk_related',
        ),
        migrations.AddField(
            model_name='related',
            name='video_02',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='BigTeta.video'),
        ),
        migrations.AlterField(
            model_name='related',
            name='video_01',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='BigTeta.video'),
        ),
        migrations.AddConstraint(
            model_name='related',
            constraint=models.UniqueConstraint(fields=('video_01', 'video_02'), name='pk_related'),
        ),
    ]
