# Generated by Django 4.0.4 on 2022-06-24 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0004_alter_video_date_published_alter_video_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 10, 18, 35, 177629), null=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_updated',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 10, 18, 35, 177656), null=None),
        ),
    ]
