# Generated by Django 4.0.4 on 2022-06-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0005_remove_related_pk_related_related_video_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related',
            name='video_01',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='BigTeta.video'),
        ),
        migrations.AlterField(
            model_name='related',
            name='video_02',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='BigTeta.video'),
        ),
    ]
