# Generated by Django 4.0.4 on 2022-06-24 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigTeta', '0006_alter_video_date_published_alter_video_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 18, 44, 48, 954134), null=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_updated',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 6, 24, 18, 44, 48, 954160), null=None),
        ),
    ]
