from ubuntu:20.04
env DEBIAN_FRONTEND=noninteractive
run apt update
run apt -y upgrade
#install nginx dependencies
run apt install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev libxml2 libxml2-dev uuid-dev
expose 80
#get curl
run apt install -y curl
#get nginx 
workdir ~
run curl -o ~/nginx-1.21.6.tar.gz 'http://nginx.org/download/nginx-1.21.6.tar.gz' 
run tar -xzvf ~/nginx-1.21.6.tar.gz
#get rtmp module
run apt install unzip
run curl  -o nginx-rtmp-module-1.2.2.zip https://codeload.github.com/arut/nginx-rtmp-module/zip/refs/tags/v1.2.2
run unzip nginx-rtmp-module-1.2.2.zip 
#build nginx with the plugin
workdir nginx-1.21.6/
#--http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --modules-path=/etc/nginx/modules
run sh configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --with-pcre  --with-http_ssl_module --with-http_image_filter_module=dynamic  --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module --add-module=../nginx-rtmp-module-1.2.2 --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --modules-path=/etc/nginx/modules
run make
run make install
#start nginx
#run service nginx start
#install inotify-tools
run apt install -y inotify-tools
# watch for changes in the nginx config file
entrypoint  while inotifywait -q -e modify /project; do (cd /project && make); done