from nginx:1.21.6
expose 80
copy ./project/nginx.conf /etc/nginx/nginx.conf
run wget https://github.com/watchexec/watchexec/releases/download/cli-v1.19.0/watchexec-1.19.0-i686-unknown-linux-musl.tar.xz
run tar -xvf watchexec-1.19.0-i686-unknown-linux-musl.tar.xz
run export PATH="watchexec-1.19.0-i686-unknown-linux-musl:$PATH"
entrypoint []