from python:latest

env DEBIAN_FRONTEND=noninteractive
#install inotify-tools
run apt update
run apt upgrade -y
run apt install -y inotify-tools
# watch for changes in the nginx config file
entrypoint  while inotifywait -q -e modify /project; do (cd /project && make); done